### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by WatashiwaSid** [cyberboysumanjay/ocrbot#1]
I've used this source code to make my bot, and made all changes in the source code but the bot is only replying to command handlers. Whenever I'm passing image or any text I'm getting no response from the bot.

**Comment by cyberboysumanjay** [comment]
Try with a clearer picture or test it with the image specified in the source.
In complex images the bot may not detect the text in it

**Comment by WatashiwaSid** [comment]
Thanks for the early response. I wasn't expecting the response to come this
soon from a developer. I'll try what you've told. And you really make good
quality content on YouTube, please make more videos.

**Comment by Guru-25** [comment]
I am getting this error how to fix this

      
Application Logs
2020-11-13T16:10:32.948917+00:00 app[worker.1]: AttributeError: 'CallbackContext' object has no attribute 'message'
2020-11-13T16:10:32.948917+00:00 app[worker.1]: 
2020-11-13T16:10:32.948918+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-11-13T16:10:32.948918+00:00 app[worker.1]: 
2020-11-13T16:10:32.948918+00:00 app[worker.1]: Traceback (most recent call last):
2020-11-13T16:10:32.948919+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 441, in process_update
2020-11-13T16:10:32.948919+00:00 app[worker.1]:     self.dispatch_error(update, e)
2020-11-13T16:10:32.948920+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 638, in dispatch_error
2020-11-13T16:10:32.948920+00:00 app[worker.1]:     callback(update, context)
2020-11-13T16:10:32.948974+00:00 app[worker.1]: TypeError: error() missing 1 required positional argument: 'error'

**Comment by cyberboysumanjay** [comment]
Check the versions of ptb

**Comment by Guru-25** [comment]
> Check the versions of ptb

Yea after changing python-telegram-bot to python-telegram-bot==12.1.0 ,bot is starting but when i send images its not responding.

![Screenshot_2020-11-15-15-51-21-990](https://user-images.githubusercontent.com/70903440/99182340-73e72480-275a-11eb-9c4d-f206375fcee2.jpeg)

**Comment by cyberboysumanjay** [comment]
Send logs. Maybe you haven't added tesseract buildpacks

**Comment by Guru-25** [comment]
> Send logs. Maybe you haven't added tesseract buildpacks

[sgghuuh-logs-1605437471228.txt](https://github.com/cyberboysumanjay/ocrbot/files/5542225/sgghuuh-logs-1605437471228.txt)

**Comment by Guru-25** [comment]
> Send logs. Maybe you haven't added tesseract buildpacks

2020-11-15T10:50:19.863452+00:00 heroku[worker.1]: State changed from starting to up
2020-11-15T10:50:23.387671+00:00 app[worker.1]: ocrbot.py:54: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
2020-11-15T10:50:23.387694+00:00 app[worker.1]:   updater = Updater(ocr_bot_token)
2020-11-15T10:50:23.834190+00:00 app[worker.1]: 2020-11-15 10:50:23,833 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2020-11-15T10:50:24.937222+00:00 heroku[worker.1]: Process exited with status 0
2020-11-15T10:50:52.837824+00:00 app[api]: Scaled to worker@0:Free by user tusfhjbjohfy@gmail.com
2020-11-15T10:50:52.924599+00:00 heroku[worker.1]: State changed from up to down
2020-11-15T10:50:54.207004+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2020-11-15T10:50:54.268933+00:00 app[worker.1]: 2020-11-15 10:50:54,268 - telegram.ext.updater - INFO - Received signal 15 (SIGTERM), stopping...
2020-11-15T10:50:54.508018+00:00 app[api]: Scaled to worker@1:Free by user tusfhjbjohfy@gmail.com
2020-11-15T10:50:57.998246+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2020-11-15T10:50:58.112725+00:00 app[worker.1]: 2020-11-15 10:50:58,112 - telegram.ext.updater - WARNING - Exiting immediately!
2020-11-15T10:50:58.237066+00:00 heroku[worker.1]: Process exited with status 1
2020-11-15T10:50:59.184023+00:00 heroku[worker.1]: Starting process with command `python3 ocrbot.py`
2020-11-15T10:50:59.933929+00:00 heroku[worker.1]: State changed from starting to up
2020-11-15T10:51:03.680410+00:00 app[worker.1]: ocrbot.py:54: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
2020-11-15T10:51:03.680433+00:00 app[worker.1]:   updater = Updater(ocr_bot_token)
